### ISSUE TITLE
New article: setting up TailwindCSS in Adonis 5 with the default Webpack Encore package

### ISSUE THREAD

**Issue by ivan-prats** [adonisjs-community/awesome-adonisjs#52]
Hello! This is my first time writing an article about Adonis 5, so feel free to tell me any reason why this might not make the cut so I can learn about it.

The article is [here](https://ivanprats.dev/blog/set-up-tailwindcss-in-new-adonis5)

Also, I don't think I saw a prefered way of contributing explained in the CONTRIBUTING.md file, between an issue and a pull request. But if you prefer a PR: I will open one no problem

**Comment by RomainLanz** [comment]
Hey @ivan-prats! 👋 

Could you please create a PR to add your article to the list?
Thanks!
